spring:
  profiles:
    active: ${APP_PROFILE:test}
  application:
    name: user-ms
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
server:
  port: ${PORT:8099}