spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: ws-user
    password: ws-user
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
jwt:
  secret: Kal!w4re!ea5
  expiration: 86400000
user:
  deletion:
    days: 10
    cron: 1 * * * * ?